# ==========================================
# FLYWAY
# ==========================================
quarkus.flyway.migrate-at-start=true
# Le decimos a Flyway que corra sobre el datasource por defecto (DB2)
quarkus.flyway.baseline-on-migrate=true

# ==========================================
# 1. DB2 (Datasource por defecto)
# ==========================================
quarkus.datasource.db-kind=db2
quarkus.datasource.username=<user>
quarkus.datasource.password=<pass>
quarkus.datasource.jdbc.url=jdbc:db2://localhost:50000/dev_db
# Quarkus Dev Services levantará la imagen de DB2 automáticamente.
# Importante: La imagen de DB2 es pesada y requiere aceptar la licencia.
#quarkus.datasource.devservices.image-name=icr.io/db2_community/db2:latest
#quarkus.datasource.devservices.accept-eula=true

# Hibernate ORM (Escritura)
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false

# Apaga el health check automático de base de datos
quarkus.datasource.health.enabled=false

# ==========================================
# POOL DE CONEXIONES
# En Quarkus, el gestor de pool de conexiones por defecto es Agroal.
# Es un pool de altísimo rendimiento y su configuración se realiza completamente a través del
# archivo application.properties
# ==========================================

# Número mínimo de conexiones que siempre estarán abiertas esperando peticiones
#quarkus.datasource.jdbc.min-size=5

# Número máximo de conexiones simultáneas permitidas (Por defecto es 20)
#quarkus.datasource.jdbc.max-size=50

# Conexiones que se crean al arrancar la aplicación (usualmente igual al min-size)
#quarkus.datasource.jdbc.initial-size=5

## Configuración Avanzada (Tiempos y Salud)

# Tiempo máximo que un hilo (petición) esperará para obtener una conexión libre
# antes de lanzar un error TimeoutException (S = Segundos)
#quarkus.datasource.jdbc.acquisition-timeout=30S

# Tiempo máximo que una conexión puede estar inactiva (sin uso) antes de que
# el pool la cierre para liberar recursos en la base de datos (M = Minutos)
#quarkus.datasource.jdbc.idle-removal-interval=5M

# Cada cuánto tiempo Agroal hará un "ping" a las conexiones inactivas en segundo
# plano para asegurarse de que la base de datos no las cerró (M = Minutos)
#quarkus.datasource.jdbc.background-validation-interval=2M

# Tiempo máximo que puede durar una transacción (query) antes de ser cancelada
# automáticamente (muy útil para evitar que queries malos bloqueen tu BD)
#quarkus.transaction-manager.default-transaction-timeout=60S